version: "3.9"

services:
  receiptai:
    image: verrenangelinas/receipt-ai:latest
    container_name: receipt
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - receipt_data:/app/data
    restart: unless-stopped

volumes:
  receipt_data:
